### ISSUE TITLE
Error with command: npm start

### ISSUE THREAD

**Issue by mohamedmehdigara** [xxxsf/react-redux-tutorial#14]

**Comment by xxxsf** [comment]
what vision of your node?

**Comment by mohamedmehdigara** [comment]
node version: v16.15.0

**Comment by xxxsf** [comment]
This project is too old, and i have refactored it, you can git pull now.

**Comment by mohamedmehdigara** [comment]
git pull ====> Already up to date.

**Comment by xxxsf** [comment]
Are you sure, check it:
![image](https://user-images.githubusercontent.com/14307551/170491893-701de6d3-423c-498d-b7ef-f55cae366272.png)
