### ISSUE TITLE
请教一下关于使用方面的问题

### ISSUE THREAD

**Issue by Armyoftheworld** [xxxsf/react-redux-tutorial#3]
大佬你好，我想请教几个问题：

1. 我现在不打算用typescript，请问要去掉哪些相关的配置？
2. 我想要调用真实的接口，请问我需要改哪些？我看npm start的时候默认起了一个服务当成服务器。

**Comment by xxxsf** [comment]
1、在webpack中移除ts的配置
2、直接调用就行了，不必管npm start的
